Use pybind11 dtype::itemsize() instead of removed elsize()
pybind11::dtype::elsize() is not present in current pybind11 (required
for Python 3.14 / NumPy 2 support); the equivalent accessor is
itemsize(). Fixes the meshio build:
  ply_loader.h:77: error: 'class pybind11::dtype' has no member named
  'elsize'; did you mean 'itemsize'?